### ISSUE TITLE
Texts to show default cursor on hover

### ISSUE THREAD

**Issue by jackiecorn** [thomas-lowry/figma-plugin-ds#1]
Hey Tom, great work on the plugin ds!
I'm wondering if texts elements like Labels should remove the cursor change on hover, since in the native Figma UI almost all texts keeps the cursor unchanged.
What do you think?

**Comment by thomas-lowry** [comment]
Thanks! By default I believe we don't show the Figma cursors inside the iFrame/Plugin UI, but I can definitely fix it on the documentation site (if I am understanding correctly)?

**Comment by jackiecorn** [comment]
![cursor](https://user-images.githubusercontent.com/6892625/63992240-cf6abb00-ca9f-11e9-974a-8819dfad3e8a.gif)
Are you sure the cursor is not shown in the iFrame? I'm seeing this in mine, using the DS styling.

**Comment by thomas-lowry** [comment]
ohhh, I misread and thought you meant the custom move cursor from Figma UI. Yes I will fix this this morning. Thanks!

**Comment by thomas-lowry** [comment]
https://github.com/thomas-lowry/figma-plugin-ds/commit/777c2ff07bf2e07aa8d0636e34eb002171adfdff

Fixed!
