### ISSUE TITLE
Buttons not reacting to presses correct

### ISSUE THREAD

**Issue by victorb** [thomas-lowry/figma-plugin-ds#10]
Seems when you press the button, it keeps it in the `clicked`/`active` state until you click on something outside of it, instead of just doing it when clicking on it.

Could try to fix this, but blocked because of https://github.com/thomas-lowry/figma-plugin-ds/issues/8

**Comment by jackiecorn** [comment]
You can fix this by adding this to your button tag:
`onclick="this.blur()"`

**Comment by victorb** [comment]
Thanks! Will give that a try. Now we're just waiting for #8 so it can be fixed properly for everyone :)
