### ISSUE TITLE
selectmenu programatically trigger?

### ISSUE THREAD

**Issue by greg-wolff** [thomas-lowry/figma-plugin-ds#16]
Is there a way to alter the selected item of a [selectMenu](https://github.com/thomas-lowry/figma-plugin-ds/blob/master/js/selectMenu.js) programatically? I see the [`selectedItem`](https://github.com/thomas-lowry/figma-plugin-ds/blob/master/js/selectMenu.js#L16) variable in the code, but wasn't sure if this was a private variable, seems to be no instance functions associated with it.

**Comment by thomas-lowry** [comment]
Looking into this, this weekend. Lots of updates planned for this particular component.

**Comment by thomas-lowry** [comment]
Fixed in latest release, now available as an npm package.
