### ISSUE TITLE
Select menu broken, if there are no options

### ISSUE THREAD

**Issue by gossi** [thomas-lowry/figma-plugin-ds#17]
Hey,

fantastic job on this UI toolkit for figma plugins. I just used it and I figured there is a bug with the select-menu. It fails and breaks everything after, if there are no options.

<img width="488" alt="Bildschirmfoto 2019-12-30 um 18 57 10" src="https://user-images.githubusercontent.com/283700/71593988-5c994b80-2b36-11ea-8832-a790baccb705.png">

Here is a screenshot I took from current development.

Looks like this is the affected line:

https://github.com/thomas-lowry/figma-plugin-ds/blob/f58d127fae0f0e566ca834b3e48bbbb5e1939dc9/js/selectMenu.js#L131

as this is the only `.selected` occurence ;)

My workaround is, that I only add the class `class="select-menu"` if I know I have options to that select and run the init after.

**Comment by gossi** [comment]
The workaround didn't work quite as expected. So I got another NPE. Here is the trace:

<img width="420" alt="Bildschirmfoto 2019-12-31 um 14 00 45" src="https://user-images.githubusercontent.com/283700/71622445-0d0a5c80-2bd6-11ea-9617-8831b35f4160.png">

That is given to how the DOM looks like now, I guess this line:

https://github.com/thomas-lowry/figma-plugin-ds/blob/f58d127fae0f0e566ca834b3e48bbbb5e1939dc9/js/selectMenu.js#L373

I'm also perhaps using this component in the wrong way. I meanwhile put my own code on GH, find it here: https://github.com/gossi/figma-style-references/

I will comment out the lines that invoke the `selectMenu` (so you can search for it in `ui/ui.ts`)

**Comment by thomas-lowry** [comment]
Thanks for flagging this and for your patience while addressing this. Addressed in an update of this that I am releasing.

https://github.com/thomas-lowry/figma-plugin-ds/pull/25

**Comment by thomas-lowry** [comment]
Fixed in the latest release which is now available as an npm package.
