### ISSUE TITLE
Handlers on selectMenu do not work

### ISSUE THREAD

**Issue by Andreslav** [thomas-lowry/figma-plugin-ds#2]
Probably after changing selectMenu it is worth calling `select.dispatchEvent (new Event ('change'))` for the handlers to work?

**Comment by herrmannplatz** [comment]
Using the following snippet should also work in react scenarios.

```
const event = document.createEvent('HTMLEvents');
event.initEvent('change', true, false);
select.dispatchEvent(event);
```

**Comment by thomas-lowry** [comment]
Thanks everyone. I am still looking into more event handlers to add but for the time being I have updated it to have onchange trigger an event. Thank you!
