### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by romannurik** [thomas-lowry/figma-plugin-ds#22]
It'd be great if these components (JS/CSS/SCSS/etc) were published to npm!

**Comment by romannurik** [comment]
Additionally, to publish to NPM it'd be great to pick an OSS license :) (Apache/MIT/etc)

**Comment by craigmdennis** [comment]
Created a PR https://github.com/thomas-lowry/figma-plugin-ds/pull/24 to add a package.json with an ISC licence in the hopes of moving this forward.

**Comment by thomas-lowry** [comment]
Fixed in the latest release which is now available as an npm package and a build using Gulp 4. Thanks for all of your help.

**Comment by alexandrtovmach** [comment]
Could you add installation guide and link to NPM package to README
