### ISSUE TITLE
The menu of a <select> control doesn't refresh when it is dynamically populated with <option>

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [thomas-lowry/figma-plugin-ds#23]
I have a `select` control that uses the figma-plugin-ds CSS. When I dynamically populate it with multiple `option` elements using JavaScript, the menu only shows the options that existed before adding them (even though in the code they are there). Is there a way to force the control to refresh?

If I use a native, non-skinned, `select` control I can see the dynamically added `option` elements.

**Comment by thomas-lowry** [comment]
@Jeremy-Knudsen Working to address this and just submitted a PR with a redesigned select menu. Getting a couple more things ready and then I will merge.

https://github.com/thomas-lowry/figma-plugin-ds/pull/25

**Comment by thomas-lowry** [comment]
Fixed in the latest release which is now available as an npm package.
