### ISSUE TITLE
Backward compatibility is broken?

### ISSUE THREAD

**Issue by alexandrtovmach** [thomas-lowry/figma-plugin-ds#29]
I just checked classnames for components, and it seems not backward compatible with previous realization. For sure it looks better, because it's kind of BEM, but good to mention this in README

**Comment by thomas-lowry** [comment]
I mentioned it in the PR. Calls I had to make to simplify markup to maintain closer relationship to the Svelte version for maintainability. Checkboxes and switches I believe were the main ones and phased out use of the mixins for type to reduce any dependency on sass to use it. 

Will do my best to avoid breaking changes in the future but can’t guarantee.
