### ISSUE TITLE
Any way to make the Select Menu work with React?

### ISSUE THREAD

**Issue by sntiagomoreno** [thomas-lowry/figma-plugin-ds#36]
Would appreciate any help or directions! Thanks!

OnChange event simply won't fire ☹️

**Comment by alexandrtovmach** [comment]
Feel free to use ported react library [react-figma-plugin-ds](https://github.com/alexandrtovmach/react-figma-plugin-ds), see [demo here](https://alexandrtovmach.github.io/react-figma-plugin-ds/)
