### ISSUE TITLE
Spinning icon is not centered correctly

### ISSUE THREAD

**Issue by didoo** [thomas-lowry/figma-plugin-ds#38]
When an icon (in particular the spinner) is spinning, the center of the icon has an offset that makes the animation look wrong:
![Screen Recording 2020-09-09 at 11 25 19](https://user-images.githubusercontent.com/686239/92587356-6e1f1f80-f28f-11ea-8688-b6392759a077.gif)

You can see a live demo here:
https://codesandbox.io/s/vigilant-dubinsky-ywl8q?file=/index.html

It is caused by this line:
https://github.com/thomas-lowry/figma-plugin-ds/blob/e1acbac7a56937b784b34366bcd7ca7386280253/src/styles/components/_icon.scss#L11
which I have no idea why it was introduced. Looks a strange declaration to me, probably should just be:
```
background-position: 50% 50%;
```

Do you think we can fix this? Happy to open a PR for this.

**Comment by taitems** [comment]
Just hit this one myself, if you don't feel like making a PR I will?

**Comment by didoo** [comment]
@taitems you can try but I can't see much activity on the repo, so I suspect it will not be picked up (that's why I didn't). if you want to try, more than happy (in that case I'll submit other PRs for other issues).

**Comment by thomas-lowry** [comment]
I just updated this! thank you for flagging.
