### ISSUE TITLE
Add a "flex: none" to the icon when is inside the Onboarding Tip

### ISSUE THREAD

**Issue by didoo** [thomas-lowry/figma-plugin-ds#40]
https://github.com/thomas-lowry/figma-plugin-ds/blob/e1acbac7a56937b784b34366bcd7ca7386280253/dist/figma-plugin-ds.css#L1527-L1529

The icon should have a flex none applied to it, when is inside the Onboarding Tip:
```
.onboarding-tip .icon {
  flex: none;
}
```
otherwise when the Onboarding Tip is used in a small horizontal container and the text is long, the icon collapses its size.

**Comment by thomas-lowry** [comment]
Updated this today! Thank you!
