### ISSUE TITLE
Disclosures not working in React UI

### ISSUE THREAD

**Issue by brianlovin** [thomas-lowry/figma-plugin-ds#6]
Hey Thomas - I can't seem to get the Disclosures to work out of the box in a React UI. Clicking on them doesn't seem to be swapping the `--expanded` class properly. If I add it manually in the React code it does get the correct `--expanded` styling, so I think the issue may be somewhere in the JS itself.

**Comment by brianlovin** [comment]
I missed the `disclosure.init();` code, whoops

**Comment by alexandrtovmach** [comment]
@brianlovin Hello, could you provide an example how and where do you initialize `disclosure` in react application
